// <auto-generated />
using DrinkApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace DrinkApi.Migrations
{
	[DbContext(typeof(DrinkContext))]
	partial class DBContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

			modelBuilder.Entity("DrinkApi.Models.Drink", b =>
				{
					b.Property<int?>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("StrDrink")
						.HasMaxLength(50)
						.HasColumnType("TEXT");

					b.Property<string>("StrDrinkThumb")
						.HasColumnType("TEXT");

					b.HasKey("Id");

					b.ToTable("Drinks");
				});
#pragma warning restore 612, 618
		}
	}
}
